server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SPRINGSECURITY
    username: spring
    password: password
    initialization-mode: always
  jpa.hibernate.ddl-auto: none