/*
user/pass
admin/pass
*/

INSERT INTO USERS (USERNAME, PASSWORD, ENABLED) VALUES ('USER', '$2a$10$Kyx/pEaok6sAOGqPOYlhMe2pZrrAS3ru8UXK9DmUcsIZpV0q2Fl4W', 1);
INSERT INTO USERS (USERNAME, PASSWORD, ENABLED) VALUES ('ADMIN', '$2a$10$Kyx/pEaok6sAOGqPOYlhMe2pZrrAS3ru8UXK9DmUcsIZpV0q2Fl4W', 1);

INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES ('USER', 'ROLE_USER');
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES ('ADMIN', 'ROLE_ADMIN');